import json
import logging
from typing import Optional

import requests

logger = logging.getLogger(__name__)


class OllamaTranslator:
    """
    Translates text using local Ollama instance.
    """

    def __init__(self, model: str = "llama3.1", base_url: str = "http://localhost:11434"):
        self.model = model
        self.base_url = base_url
        self.api_url = f"{base_url}/api/generate"
        self.pull_url = f"{base_url}/api/pull"

    def pull_model(self) -> bool:
        """
        Pull the required model via Ollama API with streaming progress.
        """
        logger.info(f"Pulling model '{self.model}' via Ollama API...")
        try:
            payload = {"model": self.model, "stream": True}
            # Large models can take substantial time to download; use a long timeout (1 hour) for the streaming pull
            response = requests.post(self.pull_url, json=payload, stream=True, timeout=3600)
            response.raise_for_status()

            import json

            for line in response.iter_lines():
                if line:
                    status = json.loads(line.decode("utf-8"))
                    if "status" in status:
                        # Log progress to keep connection alive and inform user
                        current = status.get("completed", 0)
                        total = status.get("total", 0)
                        if total > 0:
                            percent = (current / total) * 100
                            logger.info(f"Ollama Pull [{self.model}]: {status['status']} ({percent:.1f}%)")
                        else:
                            logger.info(f"Ollama Pull [{self.model}]: {status['status']}")

            logger.info(f"Successfully pulled model '{self.model}'")
            return True
        except Exception as e:
            logger.error(f"Failed to pull model '{self.model}' via API: {e}")
            return False

    def translate(self, text: str, target_lang: str, context: Optional[str] = None) -> dict:
        """
        Translate text to target language with optional context.

        Returns:
            dict: {"text": str, "tts_instruction": str} - Translated text and TTS guidance
        """
        if not text.strip():
            return {"text": "", "tts_instruction": ""}

        prompt = f"""
        You are translating game dialogue from English to {target_lang}.
        Maintain the character's tone, emotion, and any specific gaming terminology.

        Respond in JSON format with two fields:
        1. "text": The translated dialogue (ONLY the translation, no explanations)
        2. "tts_instruction": A brief instruction for voice synthesis that specifies the accent/dialect variant
           (e.g., for "Brazilian Portuguese" use "Brazilian Portuguese accent and pronunciation",
            for "European Portuguese" use "European Portuguese accent and pronunciation",
            for "American English" use "American English accent", etc.)

        {f"Context: {context}" if context else ""}

        Text to translate:
        ###
        {text}
        ###

        Respond with valid JSON only:
        """

        logger.info(f"Translating text: {text[:50]}...")

        try:
            payload = {
                "model": self.model,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {"temperature": 0.3},
            }

            response = requests.post(self.api_url, json=payload, timeout=120)

            if response.status_code == 404:
                logger.error(f"Ollama model '{self.model}' not found. Please run 'ollama pull {self.model}'")
                return {"text": text, "tts_instruction": ""}

            response.raise_for_status()

            result = response.json()
            response_text = result.get("response", "").strip()

            if not response_text:
                logger.warning("Ollama returned empty response. Using original text.")
                return {"text": text, "tts_instruction": ""}

            try:
                parsed = json.loads(response_text)
                translated_text = parsed.get("text", "").strip().strip('"')
                tts_instruction = parsed.get("tts_instruction", "").strip().strip('"')

                if not translated_text:
                    logger.warning("Ollama returned empty translation. Using original text.")
                    return {"text": text, "tts_instruction": tts_instruction}

                logger.info(f"Translation successful: {translated_text[:50]}...")
                if tts_instruction:
                    logger.info(f"TTS instruction: {tts_instruction}")
                else:
                    logger.warning("No TTS instruction generated by LLM")
                return {"text": translated_text, "tts_instruction": tts_instruction}
            except json.JSONDecodeError as e:
                logger.warning(f"Failed to parse JSON response: {e}")
                logger.warning(f"Raw response: {response_text[:200]}...")
                # Fallback: treat the entire response as translated text
                return {"text": response_text, "tts_instruction": ""}

        except Exception as e:
            logger.error(f"Ollama translation failed: {e}")
            return {"text": text, "tts_instruction": ""}


if __name__ == "__main__":
    # Basic test (requires Ollama running)
    logging.basicConfig(level=logging.INFO)
    translator = OllamaTranslator()
    # print(translator.translate("Stay alert, the enemies are approaching!", "Portuguese"))
